# 03-security/eso-store.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: prod-ns
spec:
  provider:
    gcpsm:
      projectID: "second-project-497312"
      auth:
        workloadIdentity:
          clusterLocation: "us-central1"
          clusterName: "dev-cluster"
          serviceAccountRef:
            name: "backend-ksa" # The KSA we created earlier
